language: java
jdk: openjdk11
os: linux
dist: xenial
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
install:
- ./scripts/install.sh
script:
- ./scripts/build.sh
before_cache:
- rm -rf $HOME/.m2/repository/org/opencds/cqf/cql
notifications:
  slack:
    - rooms:
      - secure: ls3HU68fKzvrgvXTWK1YSof2IV9Yc2G+xHi/L/SZZMseEZyBLy70ufK559IArnr/g0Zmp0XGIYCIpawTRNa9AuR09UcQBBRkoKKb8UqGwW+DXaBRAHUJKf7Fzt1JnsbxjHQam+AVC3MKmvN+9ardWIFHxa8FsCkG+11AHUrmRkeyt0Jx6KzJHZLOTqkSZCGplj3DfXVMArDM6zYaPwD82kEjQkLD75Ul+FQ9S83d+DN2q9aPxGa782v/qFHi068br7tnFvku7U7CoxcI1vuzsXmqZOHj7MGrcMCrVxEVmoN85ffIFdS8/N+o3kGxGv6TrDHvXUsPSkPY20n1Cg9V96IG3UL+qsa3bd1aBC8mjPUrmbCYb+Puk69raJbTO6DZ+0zOQFtKD6KVUzthsTHhkkPYO1OjDayD2ajBFipkdzg4nUvPFf7jdHoQh9dUmiqZ2TIU07digzq4B8fCOs/bJUxld+rsXreU20TFi9b/UHB6836wkzp3PCr0uI7oSwQWDhGeR+LRERsprVN+dHLxrA7eJupeHI33Ipx3GuufMPc0pYJ7J7NYBqioW4COdYZR++BDQzh7kYdBRzgH/oYw2gzGc0Gdig8b0TVhxn/mJtpoKdJfuMH4Q8UDC+qXxvv//Zz3jjDLpGVaY8bAGGFiY48AfXzNC7muy+Fp4SOdmFQ=
      on_success: always
      on_failure: never
    - rooms:
      - secure: ZQknG9N6kaPDhrRBdOfHWS5zvFoLRrNX1aJff3NKagXVOONjMyvkpfgfleVnnLbiQ/sxjpjBgLrBAVRaSCNEHxyVFwLwlKxNzJb3sndaj/0+sOgCeOjC/RSFTaOz+Rv1T8ezJI1MMqOiVBJHPcpTdndcNQzJT30nAHqKXkeqWgXE/g444RmV5aYCziInDSjLX08f5GPF+hjY9kT+JGDLYaLcNFTdWi6TkUmYM8XjRtGW1d7Gv4hXCdK0i8tm0/p5gdZ0njx5GiegTrNfB5FWKmA3Z9ZZugPb84tgsXSsNP3ps3fA9Hp3kBwDTDCBLrbX2LB5fOHrHUg1N6sghDGcwMru4OeQ6g3H0lxBM7uy1ZpvH7DGGfPSY3FkOrQBIiGnyF5SQg+Qi7TPeTgF+Nb80UAcpupBhQS1u8P65eyqNXdbPszrFSQFKhFU5NwalniUasWyVFfOkjB/dBqUgkO9vOFwQdjZw+bMmH9j3qqmSDrpHU1NHW4SJmjZWDhEfuYG9F02S9Xinr8egzwAx0K7NdDuPpOT+fzfGfFib/835lj3ZUJPfZNXucw8AoDQfiLd08k4lsIGr8W6DRcQPzM/YAPoOVgDjkevx9OXMFRhPr6yB54J17dn4y6RpjLkgemi+o/XvYDI+7WwN17skbof1qV0g0mbqGJx41aw5Tqbgkg=
      on_success: never
      on_failure: always
  
